"""create users and ownership fks

Revision ID: da1310998d52
Revises: 
Create Date: 2025-09-27 14:44:00.713676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da1310998d52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('logged_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('purchases', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'sessions_remaining',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'purchase_date',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchases', 'cost',
               existing_type=mysql.DOUBLE(asdecimal=True),
               server_default=None,
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_purchases_duration_minutes'), 'purchases', ['duration_minutes'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.create_foreign_key(None, 'purchases', 'users', ['logged_by_user_id'], ['id'])
    op.add_column('sessions', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('sessions', 'purchase_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'session_date',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sessions', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'trainer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_sessions_session_date'), 'sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_sessions_trainer'), 'sessions', ['trainer'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_trainer'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_date'), table_name='sessions')
    op.alter_column('sessions', 'trainer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sessions', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'session_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('sessions', 'purchase_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('sessions', 'created_by_user_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_duration_minutes'), table_name='purchases')
    op.alter_column('purchases', 'cost',
               existing_type=sa.Float(),
               server_default=sa.text("'0'"),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=False)
    op.alter_column('purchases', 'purchase_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('purchases', 'sessions_remaining',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('purchases', 'logged_by_user_id')
    # ### end Alembic commands ###
