"""Add trainers table and trainer_id to sessions

Revision ID: ed03ff5b3f5c
Revises: da1310998d52
Create Date: 2025-09-28 20:19:32.804524

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed03ff5b3f5c'
down_revision: Union[str, Sequence[str], None] = 'da1310998d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainers_id'), 'trainers', ['id'], unique=False)
    op.create_index(op.f('ix_trainers_name'), 'trainers', ['name'], unique=False)
    op.add_column('sessions', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'trainers', ['trainer_id'], ['id'])

    # Seed default trainers
    trainers_table = sa.table('trainers',
        sa.column('name', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime)
    )

    op.bulk_insert(trainers_table, [
        {'name': 'Rachel', 'is_active': True, 'created_at': datetime.utcnow()},
        {'name': 'Lindsay', 'is_active': True, 'created_at': datetime.utcnow()}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'trainer_id')
    op.drop_index(op.f('ix_trainers_name'), table_name='trainers')
    op.drop_index(op.f('ix_trainers_id'), table_name='trainers')
    op.drop_table('trainers')
    # ### end Alembic commands ###
