# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        # … your existing MySQL service config …

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package
        run: pip install --upgrade pip && pip install -e .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: mysql+pymysql://user:pass@localhost:3306/gym_tracker
        run: pytest --maxfail=1 --disable-warnings -q
